name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build
    - name: Rename files
      run: |
        cd dist
        mv index-linux hide-scores-linux
        mv index-macos hide-scores-macos
        mv index-win.exe hide-scores-windows.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./dist
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
